Diplom 2
ksonic/Diplom_2 pull request #1
Opened 2022-05-15 17:07 UTC by ksonic

2022-05-17 06:35 UTC, nrasskosova requested changes

2022-05-17 06:35 UTC, nrasskosova commented on src/test/java/UserCreationTest.java
> +import org.junit.jupiter.params.ParameterizedTest;
лишние импорты. их нужно убирать

2022-05-17 06:35 UTC, nrasskosova commented on src/test/java/GetOrderTest.java
> +    public void orderCreateWithLoginTest() {
название методов в java формируются таким образом, что первым словом всегда должен идти глагол. нужно переименовать тесты, например, на createOrderWithLoginTest

2022-05-17 06:35 UTC, nrasskosova commented on src/test/java/OrderCreationTest.java
> +    public void orderCreateWithoutLoginTest() {
дублирование тестов: orderCreateWithoutLoginTest и orderCreateWithLoginTest в GetOrderTest

2022-05-17 06:35 UTC, nrasskosova commented on src/test/java/UserCreationWithInvalidCredentialsTest.java
> +    public void UserCreationWithInvalidCredentialsTest(User user) {
название метода не соответствует camel

2022-05-17 06:35 UTC, nrasskosova commented on src/test/java/client/IngredientClient.java
> +    // Получение ингредиентов
Все эти комментарии нужно добавить в аллюровский тег @Step. Плюс: в коде не будет комменатриев и в отчете аллюр добавятся описание шагов.

2022-05-17 06:35 UTC, nrasskosova commented on src/test/java/client/OrderGenerator.java
> +    OrderClient orderClient=new OrderClient();
лишнее. объект в данном клиассе не используется, можно удалить

2022-05-17 06:35 UTC, nrasskosova commented on src/test/java/client/OrderGenerator.java
> +    public static String json =String.format("{\n" +
константы нужно объявлять: public static final String JSON = ...
нужно исправить для всех трех

2022-05-17 06:35 UTC, nrasskosova commented on src/test/java/client/OrderGenerator.java
> +    public static String jsonInvalidIngredients =String.format("{\"ingredients\": [\"test\"]}");
тут format лишнее. Можно просто указать как строку: "{\"ingredients\": [\"test\"]}"

2022-05-23 11:58 UTC, nrasskosova commented on src/main/java/client/OrderClient.java
> +import static client.Constants.USER_PATH;
похоже, что забыла вкоммитить новый класс Constants. Добавь пожалуйста, потом продолжу ревью этого задания

2022-05-23 12:12 UTC, ksonic commented on src/main/java/client/OrderClient.java
> +import static client.Constants.USER_PATH;
Готово.

2022-05-23 12:30 UTC, nrasskosova commented on src/test/java/UserCreationWithInvalidCredentialsTest.java
> +    public void UserCreationWithInvalidCredentialsTest(User user) {
не поправлено

2022-06-12 15:05 UTC, merged